import AuthProvider from "@/src/Context/AuthProvider";
import TodoProvider from "@/src/Context/TodoProvider";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-blue-100 py-16 min-h-[150vh]">
          <AuthProvider>
            <TodoProvider>{children}</TodoProvider>
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
